from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib.colors import HexColor

OUT = '/vercel/share/v0-project/php-student-management/presentation-system-upgrades.pdf'
PAGE_W, PAGE_H = A4
NAVY = HexColor('#17324D')
BLUE = HexColor('#2563A6')
TEAL = HexColor('#2A9D8F')
LIGHT = HexColor('#F2F6FA')
MID = HexColor('#5C6B78')
DARK = HexColor('#23313D')

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='CoverTitle', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=28, leading=34, textColor=NAVY, alignment=TA_CENTER, spaceAfter=16))
styles.add(ParagraphStyle(name='CoverSub', parent=styles['Normal'], fontName='Helvetica', fontSize=13, leading=19, textColor=MID, alignment=TA_CENTER, spaceAfter=10))
styles.add(ParagraphStyle(name='H1x', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=18, leading=23, textColor=NAVY, spaceBefore=12, spaceAfter=8))
styles.add(ParagraphStyle(name='H2x', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=12.5, leading=17, textColor=BLUE, spaceBefore=9, spaceAfter=5))
styles.add(ParagraphStyle(name='Bodyx', parent=styles['BodyText'], fontName='Helvetica', fontSize=9.5, leading=14, textColor=DARK, spaceAfter=6))
styles.add(ParagraphStyle(name='Smallx', parent=styles['BodyText'], fontName='Helvetica', fontSize=8, leading=11, textColor=MID, spaceAfter=3))
styles.add(ParagraphStyle(name='Bulletx', parent=styles['BodyText'], fontName='Helvetica', fontSize=9.3, leading=13.5, leftIndent=14, firstLineIndent=-8, textColor=DARK, spaceAfter=3))
styles.add(ParagraphStyle(name='Callout', parent=styles['BodyText'], fontName='Helvetica-Bold', fontSize=10, leading=14, textColor=NAVY, backColor=LIGHT, borderColor=HexColor('#D7E4EF'), borderWidth=0.6, borderPadding=9, spaceBefore=6, spaceAfter=8))

P = lambda text, style='Bodyx': Paragraph(text, styles[style])
def bullets(items):
    return [P('• ' + item, 'Bulletx') for item in items]
def footer(canvas, doc):
    canvas.saveState()
    canvas.setStrokeColor(HexColor('#D7E4EF'))
    canvas.line(42, 30, PAGE_W-42, 30)
    canvas.setFont('Helvetica', 7.5)
    canvas.setFillColor(MID)
    canvas.drawString(42, 18, 'Saorinians Student Management System')
    canvas.drawRightString(PAGE_W-42, 18, f'Presentation guide  |  Page {doc.page}')
    canvas.restoreState()

doc = SimpleDocTemplate(OUT, pagesize=A4, rightMargin=42, leftMargin=42, topMargin=42, bottomMargin=46, title='Saorinians Student Management System - Work Explanation')
story = []

story += [Spacer(1, 1.0*inch), P('Saorinians Student Management System', 'CoverTitle'), P('Complete explanation of the implemented grading, attendance, dashboard, assignment, and reporting upgrades', 'CoverSub'), Spacer(1, 0.25*inch)]
cover = Table([[P('<b>Technology kept unchanged</b><br/>PHP + MySQL + Bootstrap + JavaScript', 'Bodyx')], [P('<b>Audience</b><br/>Students, teachers, administrators, and project evaluators', 'Bodyx')], [P('<b>Presentation purpose</b><br/>Explain what was changed, why it was needed, how it works, and what users gain from it', 'Bodyx')]], colWidths=[5.9*inch])
cover.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),LIGHT),('BOX',(0,0),(-1,-1),0.7,HexColor('#D7E4EF')),('INNERGRID',(0,0),(-1,-1),0.4,colors.white),('LEFTPADDING',(0,0),(-1,-1),14),('RIGHTPADDING',(0,0),(-1,-1),14),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]))
story += [cover, Spacer(1, 0.4*inch), P('Prepared for Friday presentation', 'CoverSub'), PageBreak()]

story += [P('1. Executive Summary', 'H1x'), P('The project was upgraded without changing its programming language or overall architecture. The system remains a PHP and MySQL student-management application using Bootstrap for the interface and JavaScript for small interactive behaviors. The work focused on making grading more structured, attendance faster, dashboards easier to understand, student submissions safer, and reports more useful on desktop and mobile devices.'), P('The main improvement is that the system now supports four grading periods and calculates grades using transparent component weights. Teachers can organize assessments by period, students can see their period results, and attendance contributes automatically to the grade.'), P('Presentation sentence: <b>We improved the existing PHP system instead of replacing it, so the new features fit the current database, authentication, teacher workflows, and student workflows.</b>', 'Callout')]

story += [P('2. Existing Technology and Architecture', 'H1x'), P('The application keeps the same technology stack. This is important because the goal was to upgrade functionality while preserving the team’s existing knowledge and deployment setup.'), P('Technology', 'H2x')]
story += [Table([[P('<b>Layer</b>','Smallx'), P('<b>Technology</b>','Smallx'), P('<b>Purpose</b>','Smallx')], [P('Application','Smallx'),P('PHP','Smallx'),P('Processes forms, sessions, permissions, page rendering, and server-side calculations.','Smallx')], [P('Database','Smallx'),P('MySQL','Smallx'),P('Stores users, sections, assessments, scores, attendance, assignments, and submissions.','Smallx')], [P('Interface','Smallx'),P('HTML + Bootstrap + CSS','Smallx'),P('Provides responsive layouts, cards, tables, forms, buttons, and mobile behavior.','Smallx')], [P('Interaction','Smallx'),P('JavaScript','Smallx'),P('Adds bulk attendance actions, confirmations, and client-side usability improvements.','Smallx')]], colWidths=[1.1*inch,1.55*inch,3.25*inch], repeatRows=1), Spacer(1,8)]

story += [P('3. Grading Period Upgrade', 'H1x'), P('The grading workflow was extended from a single general result into four named grading periods: 1st Grading, 2nd Grading, 3rd Grading, and 4th Grading. Every assessment can now be assigned to one of these periods.'), P('Why this matters', 'H2x')] + bullets(['Teachers can record assessments in the correct academic period.', 'Students can review progress instead of waiting for one final combined number.', 'The calculation is easier to explain because each period has a visible breakdown.', 'The structure can support report cards and future period-based exports.'])
story += [P('Database change', 'H2x'), P('The assessments table was extended with a <b>grading_period</b> field. This field is a small unsigned number from 1 to 4 and defaults to 1, which preserves compatibility with existing assessments. Assessment types were also expanded to include <b>module</b> and <b>test</b> while retaining the existing quiz, exam, assignment, and project types.'), P('The SQL file includes an upgrade statement for existing installations. The intention is that an existing database can be updated rather than deleted and recreated.', 'Callout')]

story += [P('4. Weighted Grade Calculation', 'H1x'), P('Each grading period uses the approved weights below. The calculation is performed by PHP database helpers so the result is consistent wherever the grade is displayed.'), Table([[P('<b>Component</b>','Smallx'),P('<b>Weight</b>','Smallx'),P('<b>Source</b>','Smallx')],[P('Attendance','Smallx'),P('10%','Smallx'),P('Attendance records for the selected period','Smallx')],[P('Modules','Smallx'),P('20%','Smallx'),P('Module assessments and assignment-style module work','Smallx')],[P('Quizzes','Smallx'),P('30%','Smallx'),P('Quiz assessment scores','Smallx')],[P('Tests','Smallx'),P('40%','Smallx'),P('Test and exam assessment scores','Smallx')]], colWidths=[2.0*inch,0.8*inch,3.1*inch], repeatRows=1), Spacer(1,8), P('Calculation process', 'H2x')] + bullets(['The system retrieves the student’s scores and the possible score for each assessment.', 'It calculates a percentage for each component using earned points compared with possible points.', 'Attendance is calculated from attendance records. Present, late, and excused are treated as attended; absent is not.', 'The component percentages are multiplied by their weights and combined into the period result.', 'If some components are still empty, the system does not crash. It calculates from available information and shows pending values where no data exists.'])
story += [P('Example: if a student has 90% attendance, 80% modules, 75% quizzes, and 85% tests, the period score is: 90×0.10 + 80×0.20 + 75×0.30 + 85×0.40 = <b>81.5%</b>.', 'Callout')]

story += [P('5. Teacher Grade Management', 'H1x'), P('The teacher grade page now supports period-aware assessment creation. When a teacher creates an assessment, they select its type, grading period, maximum score, weight, due date, and title. The assessment listing shows both its type and grading period so it is easy to distinguish similar assessments.'), P('The grade entry flow also checks that a selected assessment belongs to the current section before using it. This keeps the teacher experience aligned with the selected class and avoids displaying a score entry screen for an assessment from another section.'), P('Teacher presentation points', 'H2x')] + bullets(['Create a Module, Quiz, or Test and assign it directly to 1st–4th Grading.', 'See the assessment category and period in the listing.', 'Enter student scores through the existing grade-entry workflow.', 'Use the same PHP helper functions for consistent grade calculations.'])

story += [P('6. Student Grade View', 'H1x'), P('The student grade page now shows the existing grade information plus a period summary for each enrolled section. Students can see the result for each of the four grading periods and understand whether a period is complete or still pending.'), P('This supports a more student-friendly experience because students can identify where they are performing well and which grading period still needs work. It also makes the weighted calculation less of a “black box.”')]

story += [P('7. Attendance Improvements', 'H1x'), P('Attendance remains a fast teacher workflow. The bulk actions now include confirmation prompts so a teacher does not accidentally mark an entire class present or absent with one unintended click.'), P('Attendance status options remain clear and distinct: Present, Absent, Late, and Excused. These statuses are also used by the automatic grading calculation. Present, Late, and Excused count as attended, while Absent lowers the attendance percentage.'), P('The selected date and existing attendance workflow remain in place, which reduces disruption for teachers who already know the system.')]

story += [P('8. Assignments and Student Submissions', 'H1x'), P('The student assignment submission flow was improved so that a submission is accepted only when the student is enrolled in the assignment’s section and has entered non-empty content. This makes the submit action clearer and prevents blank or unrelated submissions from being recorded.'), P('The existing PHP submission functions remain in use. This is an incremental upgrade: the system gains a more reliable user flow without requiring a new programming language or a separate application.')]

story += [P('9. Responsive Dashboard and Mobile Usability', 'H1x'), P('The dashboard now has a clearer role-based hero area. It identifies the workspace, greets the user, explains that the page contains items requiring attention, and displays the current date. This gives both teachers and students immediate context.'), P('Mobile improvements include more usable spacing, two-column quick-action cards on small screens, responsive table handling, smaller modal margins, and card padding that fits narrow viewports. Wide tables remain horizontally scrollable instead of breaking the entire page layout.'), P('Design direction', 'H2x'), P('The interface uses a practical academic visual language: blue for primary actions and trust, white surfaces for clarity, neutral gray text for supporting information, green for successful actions, and amber/red states where attention is needed. The goal is fast scanning and low confusion rather than decorative visual effects.')]

story += [P('10. Attendance CSV Export', 'H1x'), P('Teachers can export the selected attendance report as a CSV file. The export includes student name, present count, absent count, late count, excused count, total classes, and attendance percentage. CSV was selected because it opens in spreadsheet software and can be used for reporting, analysis, or printing.'), P('This feature uses a server response with CSV headers and exits before the normal HTML page is rendered, so the downloaded file is clean and directly usable.')]

story += [P('11. Files Updated', 'H1x'), Table([[P('<b>File</b>','Smallx'),P('<b>Role in the upgrade</b>','Smallx')],[P('database.sql','Smallx'),P('Adds grading-period support, module/test types, and an upgrade path for existing databases.','Smallx')],[P('includes/db_operations.php','Smallx'),P('Adds grading period labels, attendance percentage logic, component breakdowns, and weighted grade calculations.','Smallx')],[P('modules/teacher/grades.php','Smallx'),P('Adds period selection, module/test options, period badges, and assessment-section validation.','Smallx')],[P('modules/student/my_grades.php','Smallx'),P('Shows four grading-period summaries for each section.','Smallx')],[P('modules/student/assignments.php','Smallx'),P('Validates enrollment and prevents empty assignment submissions.','Smallx')],[P('modules/teacher/attendance_report.php','Smallx'),P('Adds attendance CSV export.','Smallx')],[P('dashboard.php','Smallx'),P('Adds clearer dashboard context and responsive quick actions.','Smallx')],[P('assets/css/style.css','Smallx'),P('Adds responsive dashboard, card, table, modal, and mobile styles.','Smallx')],[P('assets/js/main.js','Smallx'),P('Adds confirmation prompts for bulk attendance actions.','Smallx')]], colWidths=[2.2*inch,3.7*inch], repeatRows=1)]

story += [P('12. User Benefits', 'H1x'), P('Benefits for students', 'H2x')] + bullets(['Understand grades by period and component.', 'See progress earlier instead of only seeing a final result.', 'Submit assignment work with clearer validation.', 'Use the system more comfortably on mobile devices.']) + [P('Benefits for teachers', 'H2x')] + bullets(['Organize assessments by grading period.', 'Record attendance quickly with safer bulk actions.', 'View attendance information in spreadsheet-friendly CSV format.', 'Use clearer dashboards and responsive tables on smaller screens.']) + [P('Benefits for administrators', 'H2x')] + bullets(['Keep the current PHP/MySQL system and existing user roles.', 'Add features incrementally without retraining users on a completely new platform.', 'Maintain a clearer foundation for future report cards, notifications, and analytics.'])

story += [P('13. Verification and Limitations', 'H1x'), P('The changed files were reviewed for consistency and the repository passed a whitespace/error check using <b>git diff --check</b>. PHP syntax linting was attempted, but the execution environment did not have the PHP command installed, so a live PHP syntax run could not be completed in this environment.'), P('Before production use, the team should run the database migration on a backup, test each role in the browser, confirm the MySQL version supports the migration syntax, and verify representative cases: empty grades, partial grades, late attendance, excused attendance, all four periods, and CSV downloads.'), P('Important implementation note: the automatic attendance calculation currently groups dates by calendar quarter (months 1–3, 4–6, 7–9, and 10–12) as a practical mapping for the four grading periods. If the school calendar uses different dates, the next upgrade should add explicit start and end dates for each grading period.', 'Callout')]

story += [P('14. Suggested Future Enhancements', 'H1x')] + bullets(['Add a formal announcements table and notification badges for students and teachers.', 'Add module submission records with file uploads and teacher feedback.', 'Add grade charts and downloadable PDF report cards.', 'Add assignment deadlines and overdue indicators.', 'Add filters and pagination to large assessment and attendance tables.', 'Add audit history for grade changes and attendance corrections.', 'Add automated tests and browser-based role testing.', 'Add configurable grading-period start and end dates.'])

story += [P('15. Presentation Closing', 'H1x'), P('The project demonstrates that a system can become significantly more responsive and user-friendly without changing its programming language. By extending the current PHP and MySQL architecture, the upgrade improves academic accuracy, teacher efficiency, student visibility, mobile usability, and reporting while preserving the existing foundation.'), P('Suggested closing statement: <b>Our system is now more organized, transparent, and practical for daily school use. The next stage can build on this foundation with notifications, richer analytics, file-based submissions, and formal report cards.</b>', 'Callout')]

doc.build(story, onFirstPage=footer, onLaterPages=footer)
print(OUT)
